[package]
name = "ff_cache"
version = "0.1.0"
authors = ["th0rex"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
